package harrow.core

import com.dongxiguo.fastring.Fastring.Implicits._
import scala.collection.mutable.ListBuffer
import java.io.File

/**
 * Code templates for flyweight abstractions in scala
 */
object FlyweightTemplate {

  val comments = """/**
 * 
 * This code is generated.. Do not edit this file directly as changes will be lost
 *
 */"""

  val baseImports = List(Import("harrow.core.ValuesDecoder"),
    Import("scala.collection.mutable.ListBuffer"))

  /**
   *
   */
  def generate(model: HarrowData, destPackage: String = "", path: String = "", lazyImmutable: Boolean = false): Seq[File] = {

    val namespace = model.headers.collect { case pkg: Namespace => pkg.path }.headOption.getOrElse(destPackage)

    require(!namespace.isEmpty(), { println("Flyweight generator :: package is required from either namespace header or explict arg") })
    require(!path.isEmpty(), { println("Flyweight generator :: path is required") })

    val all = model.allTypes.map(d => d.identifier -> d).toMap

    val imports = (model.headers.collect({ case imp: Import => imp }).toList ++ baseImports).map(i => fast"import ${i.path}").mkString("\n")

    val classes = model.complexDefinitions.values.map(d => {
      val generator = new FlyClassTemplate(d, lazyImmutable, model.order, all)
      (d.identifier, generator.generate)
    }).toList :::
      model.allTypes.collect { case is: Enum => is }.map(e => {
        val generator = new FlyEnumTemplate(e)
        (e.identifier, fast"$comments \n${generator.generate}".toString)
      })

    val fullPath = fast"${path}/${namespace.replace('.', '/')}/flyweights".toString
    val destinationFolder = new File(fullPath)
    destinationFolder.mkdirs()

    classes.map(generated => {
      val file = new File(destinationFolder, generated._1 + "Fly.scala")
      val content = fast"$comments \npackage ${namespace}.flyweights \n\n$imports \n\n${generated._2}\n\n".toString()
      Some(new java.io.PrintWriter(file.getAbsolutePath())).foreach { f => try { f.write(content) } finally { f.close } }
      file
    })

  }

}

/**
 *
 */
trait FlyweightGenerator {

  def generate: String

}

/**
 *
 */
class FlyEnumTemplate(definition: Enum) extends FlyweightGenerator {

  /**
   *
   */
  def generate = {

    val etrait = fast"sealed trait ${definition.identifier}Fly {\n\tdef name: String\n\tdef ordinal: Int\n}"
    val noValue = fast"""case object Empty${definition.identifier} extends ${definition.identifier}Fly {\n\tval name = ""\n\tval ordinal = -1\n}"""
    val valuesBuilder = definition.fields.map(f => {
      fast"case ${f._2} => ${f._1}"
    }).mkString("\n\t\t\t", "\n\t\t\t", fast"\n\t\t\tcase other => Empty${definition.identifier}\n\t\t}\n\t}".toString)
    val companion = fast"object ${definition.identifier}Fly {\n\tdef apply(value: Int) = {\n\t\tvalue match {$valuesBuilder \n}"
    val classDefs = definition.fields.map(f => {
      fast"""case object ${f._1} extends ${definition.identifier}Fly {\n\tval name = "${f._1}"\n\tval ordinal = ${f._2}\n}"""
    }).mkString("\n\n")

    fast"\n\n${etrait}\n\n${companion}\n\n${noValue}\n\n${classDefs}".toString()

  }

}

/**
 *
 */
class FlyClassTemplate(definition: Struct, lazyImmutable: Boolean = false, defaultOrder: ByteOrder, context: Map[String, TDefinition]) extends FlyweightGenerator {

  var fieldIndex = 0
  var pointer = 0
  var bitPointer = 0
  var lastFieldWasLessThanByte = false
  var varResolvers = ListBuffer.empty[String]
  var pointerVars = ListBuffer.empty[String]

  val modifier = if (lazyImmutable) "lazy val" else "def"

  val varSources = definition.variables.flatMap(vs => {
    vs match {
      case v @ VariableSource(variable, _) => Some(variable.pathSpec -> v)
      case _ => None
    }
  }).toMap

  val varProviders = definition.variables.flatMap(vs => {
    vs match {
      case v @ VariableProvider(variable, _, _) => Some(variable.pathSpec -> v)
      case _ => None
    }
  }).toMap

  /**
   *
   */
  def isCollectionType(datatype: FieldType): Boolean = {
    datatype match {
      case ListType(_) => true
      case SetType(_) => true
      case MapType(_, _) => true
      case _ => false
    }
  }

  /**
   *
   */
  def getFlyTypeAsString(datatype: Option[FieldType]): Option[String] = {
    val ttype = datatype match {
      case Some(x: PrimitiveType) => Some(fast"${x.toBoxed}".toString)
      case Some(DefinedType(t)) => Some(fast"${t}Fly".toString)
      case Some(ListType(x: PrimitiveType)) => Some(fast"List[${x.toBoxed}]".toString)
      case Some(SetType(x: PrimitiveType)) => Some(fast"Set[${x.toBoxed}]".toString)
      case Some(MapType(k: PrimitiveType, v: PrimitiveType)) => Some(fast"Map[${k.toBoxed},${v.toBoxed}]".toString)
      case Some(ListType(DefinedType(id))) => Some(fast"List[${id}Fly]".toString)
      case Some(SetType(DefinedType(id))) => Some(fast"Set[${id}Fly]".toString)
      case Some(x: ContainerType) => Some(fast"$x".toString)
      case None => None
    }
    ttype
  }

  /**
   *
   */
  def getConstructorArguments(target: TDefinition, useSite: Struct) = {
    val providers = target match {
      case c: Struct => c.variables.collect { case v: VariableProvider => v }
      case _ => Seq.empty[VariableProvider]
    }
    val contextArgs = providers.flatMap(p => {
      if (p.sourceContext.identifier == target.identifier) {
        None
      } else {
        val identifier = getIdentifierFromTypeName(p.sourceContext.identifier)
        val toUse = if (p.sourceContext.identifier == useSite.identifier) "Some(this)" else identifier
        Some(toUse)
      }
    }).toList.distinct
    (List("decoder", "_offset") ++ contextArgs).mkString(", ")
  }

  /**
   *
   */
  def getIdentifierFromTypeName(typeName: String) = {
    typeName.charAt(0).toString.toLowerCase + typeName.substring(1, typeName.length)
  }

  /**
   * builds a full class definition from the template and the model
   */
  def generate = {

    // build expression var sources
    val exprVars = varSources.values.map(v => {
      val typeInfo = v.path.last
      val hasOptional = v.path.map(_.scope == IsOptional).reduceLeft(_ || _)
      val defaultValue = HarrowDefaults.any(typeInfo.datatype.get)
      val valuePart = if (hasOptional) { // then build full optional resolver
        val fields = v.path.foldLeft(None: Option[String], List.empty[String])((parent, field) => {
          val accessor = (field.scope, parent._1) match {
            case (IsOptional, Some(p)) =>
              fast"$p.${field.identifier}"
            case (IsOptional, None) =>
              fast"${field.identifier}"
            case (_, Some(p)) =>
              fast"Some($p.${field.identifier})"
            case (_, _) =>
              fast"Some(${field.identifier})"
          }
          (Some(field.identifier), parent._2 :+ fast"${field.identifier} <- $accessor".toString)
        })._2.mkString("\n\t\t", "\n\t\t", "")
        fast"""{ \n\t  val maybeValue = for { 	$fields \n\t  } \n\t  yield ${v.variable.identifier} \n\t  maybeValue.getOrElse($defaultValue) \n\t}"""
      } else { // make direct variable reference
        val pathSpec = if (v.variable.path.headOption.map(_ == definition.identifier).getOrElse(false))
          v.variable.path.drop(1).mkString(".")
        else
          v.variable.pathSpec
        fast"""${pathSpec}"""
      }
      val retType = getFlyTypeAsString(typeInfo.datatype).map(s => fast":$s".toString).getOrElse("")
      fast"\tdef ${v.variable.accessor}() $retType = ${valuePart}"
    }).toList.distinct.mkString("\n\n")

    // build expression var providers as constructor args
    val additionalConstructorArgs = varProviders.values.flatMap(p => {
      if (p.sourceContext.identifier != definition.identifier) {
        val argIdentifier = getIdentifierFromTypeName(p.sourceContext.identifier)
        Some(fast"val ${argIdentifier} : Option[${p.sourceContext.identifier}Fly]".toString())
      } else {
        None
      }
    }).toList.distinct

    val fullConstructorArgs = (List("decoder: ValuesDecoder", "_pointer: Int = 0") ++ additionalConstructorArgs).mkString(", ")

    // build expression var providers as implicits
    val providerImplicits = varProviders.values.flatMap(p => {
      if (p.sourceContext.identifier != definition.identifier) {
        val argIdentifier = getIdentifierFromTypeName(p.sourceContext.identifier)
        Some(fast"\timplicit def self2${p.sourceContext.identifier}(fly: ${definition.identifier}Fly) = fly.${argIdentifier}.get\n".toString())
      } else {
        None
      }
    }).toList.distinct

    // build field definitions
    val fieldDefs = definition.fields.map(f =>
      fast"\n  ${getField(f)} ").mkString("\n")

    // flush any partial byte reads
    if (bitPointer > 0) { // sequential fields only partially reading a byte
      val by = if (bitPointer > 8) 
        bitPointer / 8
        else
          1
      pointer += by
      bitPointer = 0 // byte align by default
    }
    
    // build pointer vars
    val dynamicOffsets = varResolvers.mkString("\n")

    // context
    val pointers = pointer :: pointerVars.toList.distinct
    val flyCursor = fast"\t$modifier offset = _pointer \n\n\t$modifier sizeBytes = { \n\t\t${pointers.toList.distinct.mkString(" + ")} \n\t}"

    val (companionObject, companionImport) = if (providerImplicits.length > 0) {
      (fast"\n\nobject ${definition.identifier}Fly { \n\n${providerImplicits.mkString(",")} \n}".toString, fast"\timport ${definition.identifier}Fly._".toString)
    } else {
      ("", "")
    }
    /*
     * build full class definition
     */
    val classString = fast"\n\nclass ${definition.identifier}Fly($fullConstructorArgs) { \n\n$companionImport \n\n$flyCursor \n\n$dynamicOffsets \n\n$exprVars \n\n$fieldDefs  \n\n}"
    fast"$companionObject $classString".toString

  }

  /*
   * builds a field code snippet using all the model data available
   */
  private def getField(declaration: FieldDeclaration) = {

    fieldIndex += 1

    if (lastFieldWasLessThanByte && bitPointer > 7) { // sequential fields only partially reading a byte
      val by = if (bitPointer > 8) 
        bitPointer / 8
        else
          1
      pointer += by
      bitPointer = 0 // byte align by default
    }
    lastFieldWasLessThanByte = false // reset tracker

    val identifier = declaration.definition.identifier
    val fieldNum = declaration.definition.numericId.getOrElse(fieldIndex)
    val isCollection = declaration.definition.datatype.map(isCollectionType _).getOrElse(false)

    val instructions = declaration.instructions
    val expByteOrder = instructions.collect { case o: ExplicitByteOrder => o }.headOption.map(_.byteOrder)
    val byteWise = expByteOrder.getOrElse(defaultOrder)

    val noInput = instructions.contains(SkipCodec)
    val inputInstr = instructions.collect { case x: InputType => x }.headOption
    val containerItems = instructions.collect { case x: ContainerItems => x }.headOption
    val assignInstr = instructions.collect { case x: ConditionalInput => x }.headOption

    /*
     * 
     */
    def getInstructionsForPrimitive(inputInstr: InputType): (Fastring, Fastring, Int) = {

    
      inputInstr match {

        case Bits(1, _) =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.isBitSet(_offset, $bitPointer)")
          bitPointer += 1
          lastFieldWasLessThanByte = true
          (resolver._1, resolver._2, 0)

        case Bits(size, sizeExpr) =>
          val bitSizePointer = if (sizeExpr.isEmpty)
            fast"$size"
          else
            fast"${sizeExpr.get}"
          val readOp = if (declaration.definition.datatype.map(_ == TByte).getOrElse(false))
            fast" decoder.unpackBits(_offset, $size, $bitSizePointer).toByte"
          else
            fast" decoder.unpackBits(_offset, $size, $bitSizePointer)"
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", readOp)
          bitPointer += size
          lastFieldWasLessThanByte = true
          (resolver._1, resolver._2, 1)

        case Int8 =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getByte(_offset)")
          pointer += 1
          (resolver._1, resolver._2, 1)

        case UInt8 =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getUByte(_offset)")
          pointer += 1
          (resolver._1, resolver._2, 1)

        case Int16 =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getShort$byteWise(_offset)")
          pointer += 2
          (resolver._1, resolver._2, 2)

        case Int24 =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getInt24$byteWise(_offset)")
          pointer += 3
          (resolver._1, resolver._2, 3)

        case UInt16 =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getUShort$byteWise(_offset)")
          pointer += 2
          (resolver._1, resolver._2, 2)

        case Int32 =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getInt$byteWise(_offset)")
          pointer += 4
          (resolver._1, resolver._2, 4)

        case Int48 =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getInt48$byteWise(_offset)")
          pointer += 6
          (resolver._1, resolver._2, 5)

        case UInt32 =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getUInt$byteWise(_offset)")
          pointer += 4
          (resolver._1, resolver._2, 4)

        case Int64 =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getLong$byteWise(_offset)")
          pointer += 8
          (resolver._1, resolver._2, 8)

        case LDouble =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.getDouble$byteWise(_offset)")
          pointer += 8
          (resolver._1, resolver._2, 8)

        case Bytes(_, Some(sizeExpr), Some(fLiteral)) =>
          varResolvers += fast"\tprivate def _varSize$fieldIndex = $sizeExpr ".toString
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.slice(_offset, _varSize$fieldIndex)$fLiteral")
          pointerVars += fast"_varSize$fieldIndex".toString
          (resolver._1, resolver._2, 0)

        case Bytes(size, None, Some(fLiteral)) =>
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.slice(_offset, $size)$fLiteral")
          pointer += size
          (resolver._1, resolver._2, size)

        case Bytes(size, None, None) =>
          val coherce = if (declaration.definition.datatype.map(_ == TByte).getOrElse(false)) "(0)" else ""
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.slice(_offset, $size)$coherce")
          pointer += size
          (resolver._1, resolver._2, size)

        case Bytes(_, Some(sizeExpr), None) =>
          varResolvers += fast"\tprivate def _varSize$fieldIndex = $sizeExpr ".toString
          val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.slice(_offset, _varSize$fieldIndex)")
          pointerVars += fast"_varSize$fieldIndex".toString
          (resolver._1, resolver._2, 0)

        case ExplicitValue(v) =>
          (fast"", fast" $v", 0)

        case other =>
          throw new HarrowException(s"Cannot decode identifier [$identifier] with primitive type [${declaration.definition.datatype.get}] with instruction [$other] at [${declaration.pos}]")

      }

    }

    /*
     * 
     */
    def getInstructionsForTypeConstructor(inputInstr: InputType, datatype: DefinedType): (Fastring, Fastring) = {

      val targetType = context(datatype.identifier)
      targetType match {

        case is: Enum =>
          val baseResolver = getInstructionsForPrimitive(inputInstr)
          (baseResolver._1, fast"${datatype.identifier}Fly.apply(${baseResolver._2}.toInt)")

        case complexType => {
          inputInstr match {

            case Bytes(size, None, Some(fLiteral)) =>
              val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.slice(_offset, $size)$fLiteral")
              resolver

            case Bytes(_, Some(sizeExpr), Some(fLiteral)) =>
              val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" decoder.slice(_offset, _varSize$fieldIndex)$fLiteral")
              varResolvers += fast"\tprivate def _varSize$fieldIndex = $sizeExpr ".toString
              pointerVars += fast"_varSize$fieldIndex".toString
              resolver

            case Implied | Bytes(_, _, _) =>
              val constructArgs = getConstructorArguments(targetType, definition)
              val resolver = (fast" val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast" new ${datatype.identifier}Fly($constructArgs)")
              val sizeResolver = if (declaration.definition.scope == IsRequired) "sizeBytes" else "map(_.sizeBytes).getOrElse(0)"
              varResolvers += fast"\tprivate def _varSize$fieldIndex = $identifier.$sizeResolver ".toString
              pointerVars += fast"_varSize$fieldIndex".toString
              resolver

            case other =>
              throw new HarrowException(s"Cannot decode identifier [$identifier] of type [${declaration.definition.datatype.get}] with instruction [$other] at [${declaration.pos}]")

          }

        }
      }

    }

    /*
     * 
     */
    def getInstructionsForContainerType(inputInstr: InputType, datatype: ContainerType, containerSize: Option[ContainerItems]): Fastring = {

      datatype match {
        case MapType(_, _) =>
          throw new HarrowException(s"Map types are not support for input decoding for field [${declaration.definition.identifier}] at [${declaration.pos}] (hint: create wrapper type)")
        case _ =>
      }

      (containerSize, inputInstr) match {
        case (_, Bytes(size, sizeExpr, _)) =>
          val sizePointer = if (sizeExpr.isEmpty)
            fast"$size"
          else
            fast"${sizeExpr.get}"

          val (nestedType, buildr, mapper) = datatype match {

            case ListType(nested: PrimitiveType) =>
              val nestedInstructions = getInstructionsForPrimitive(inputInstr)
              pointer -= nestedInstructions._3
              (nested.toBoxed, nestedInstructions._2, "toList")

            case ListType(DefinedType(id)) =>
              val constructArgs = getConstructorArguments(context(id), definition)
              val resolver = fast" new ${id}Fly($constructArgs)"
              (id, resolver, "toList")

            case SetType(nested: PrimitiveType) =>
              val nestedInstructions = getInstructionsForPrimitive(inputInstr)
              pointer -= nestedInstructions._3
              (nested.toBoxed, nestedInstructions._2, "toSet")

            case SetType(DefinedType(id)) =>
              val constructArgs = getConstructorArguments(context(id), definition)
              val resolver = fast" new ${id}Fly($constructArgs)"
              (id, resolver, "toSet")

            case _ =>
              throw new HarrowException(s"Failed to decode [$identifier] with bytes instruction at [${declaration.pos}]")
          }

          varResolvers = varResolvers.filterNot(_.contains(fast"_varSize$fieldIndex".toString))
          varResolvers += fast"\tprivate def _varSize$fieldIndex = { $sizePointer } ".toString

          val resolver = nestedType match { // handle special case of arbitrary bytes
            case "Byte" =>
              fast"""val _offset = ${pointerVars.mkString(" + ")} + $pointer\n\t\t$buildr.$mapper"""
            case _ =>
              val initialOffset = fast"val _initialOffset = ${pointerVars.mkString(" + ")} + $pointer"
              val nresolver = fast"""val _byteChunk = $sizePointer \n\t\t$initialOffset\n\t\tval _data = ListBuffer.empty[$nestedType] \n\t\tvar _consumed = 0 \n\t\twhile(_consumed < _byteChunk) { 
               val _offset = _initialOffset + _consumed \n\t\t\tval _elem = $buildr \n\t\t\t_data += _elem \n\t\t\t_consumed += _elem.sizeBytes \n\t\t} \n\t\t_data.$mapper"""
              nresolver
          }

          pointerVars += fast"_varSize$fieldIndex".toString
          resolver

        case (_, ToSize(size, sizeExpr)) =>
          val sizePointer = if (sizeExpr.isEmpty)
            fast"$size"
          else
            fast"${sizeExpr.get}"
          val (nestedType, buildr, mapper) = datatype match {

            case ListType(nested: PrimitiveType) =>
              val nestedInstructions = getInstructionsForPrimitive(inputInstr)
              pointer -= nestedInstructions._3
              (nested.toBoxed, nestedInstructions._2, "toList")

            case ListType(DefinedType(id)) =>
              val constructArgs = getConstructorArguments(context(id), definition)
              val resolver = fast" new ${id}Fly($constructArgs)"
              (fast"${id}Fly".toString, resolver, "toList")

            case SetType(nested: PrimitiveType) =>
              val nestedInstructions = getInstructionsForPrimitive(inputInstr)
              pointer -= nestedInstructions._3
              (nested.toBoxed, nestedInstructions._2, "toSet")

            case SetType(DefinedType(id)) =>
              val constructArgs = getConstructorArguments(context(id), definition)
              val resolver = fast" new ${id}Fly($constructArgs)"
              (fast"${id}Fly".toString, resolver, "toSet")

            case _ =>
              throw new HarrowException(s"Failed to decode [$identifier] with 'to' codec instruction at [${declaration.pos}]")

          }

          varResolvers = varResolvers.filterNot(_.contains(fast"_varSize$fieldIndex".toString))
          varResolvers += fast"\tprivate def _varSize$fieldIndex = { ($sizePointer) - (${pointerVars.mkString(" + ")} + $pointer) } ".toString
          val initialOffset = fast"val _initialOffset = ${pointerVars.mkString(" + ")} + $pointer"

          val resolver = nestedType match { // handle special case of arbitrary bytes
            case "Byte" =>
              fast"""val _offset = ${pointerVars.mkString(" + ")} + $pointer\n\t\t$buildr.$mapper"""
            case _ =>
              val nresolver = fast"""val _byteChunk = _varSize$fieldIndex \n\t\t$initialOffset\n\t\tval _data = ListBuffer.empty[$nestedType] \n\t\tvar _consumed = 0 \n\t\twhile(_consumed < _byteChunk) { 
                val _offset = _initialOffset + _consumed \n\t\t\tval _elem = $buildr \n\t\t\t_data += _elem \n\t\t\t_consumed += _elem.sizeBytes \n\t\t} \n\t\t_data.$mapper"""
              nresolver
          }

          pointerVars += fast"_varSize$fieldIndex".toString
          resolver

        case (Some(ContainerItems(size, sizeExpr)), input) =>
          val sizePointer = if (sizeExpr.isEmpty)
            fast"$size"
          else
            fast"${sizeExpr.get}"

          pointerVars += fast"_containerVar$fieldIndex".toString

          val (buildr1, buildr2, mapper) = datatype match {

            case ListType(nested: ToSize) =>
              throw new RuntimeException(s"Cannot use both items: and to: instructions on a container.. wkwtftd : ${declaration.pos}")

            case SetType(nested: ToSize) =>
              throw new RuntimeException(s"Cannot use both items: and to: instructions on a container.. wkwtftd : ${declaration.pos}")

            case ListType(nested: PrimitiveType) =>
              val instructions = getInstructionsForPrimitive(inputInstr)
              (fast"${instructions._1}\n\t\t\t_containerVar$fieldIndex += ${instructions._3}", instructions._2, "toList")

            case ListType(DefinedType(id)) =>
              val constructArgs = getConstructorArguments(context(id), definition)
              varResolvers += fast"\tprivate var _containerVar$fieldIndex = 0 ".toString
              pointerVars += fast"_containerVar$fieldIndex".toString
              (fast"val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast"val nested = new ${id}Fly(_offset, $constructArgs) \n\t\t_containerVar$fieldIndex += nested.sizeBytes() \n\t\tnested", "toList")

            case SetType(nested: PrimitiveType) =>
              val instructions = getInstructionsForPrimitive(inputInstr)
              (fast"${instructions._1}\n\t\t\t_containerVar$fieldIndex += ${instructions._3}", instructions._2, "toSet")

            case SetType(DefinedType(id)) =>
              val constructArgs = getConstructorArguments(context(id), definition)
              varResolvers += fast"\tprivate var _containerVar$fieldIndex = 0 ".toString
              (fast"val _offset = ${pointerVars.mkString(" + ")} + $pointer", fast"val nested = new ${id}Fly(_offset, $constructArgs) \n\t\t_containerVar$fieldIndex += nested.sizeBytes() \n\t\tnested", "toSet")

            case _ =>
              throw new RuntimeException(s"Not a notion how to decode : $declaration.source")

          }
          varResolvers += fast"\tprivate var _containerVar$fieldIndex = 0 ".toString
          val resolver = fast"""(0 until $sizePointer).map(idx => \n\t\t{ \n\t\t\t${buildr1} \n\t\t\t${buildr2} \n\t\t}).$mapper """
          resolver

        case other => fast" null "

      }

    }

    /*
     * generate the block of code that returns the value
     */
    val snippet: String = (noInput, declaration.definition.datatype, inputInstr) match {

      case (true, Some(dtype), _) =>
        HarrowDefaults.any(dtype)

      case (false, Some(dtype), Some(ExplicitValue(expr))) =>
        fast"$expr".toString

      case (false, Some(dtype), Some(instruction: InputType)) =>
        dtype match {
          case _: PrimitiveType =>
            val lines = getInstructionsForPrimitive(instruction)
            fast"""${lines._1}\n\t\t${lines._2}""".toString
          case t: DefinedType =>
            val lines = getInstructionsForTypeConstructor(instruction, t)
            fast"""${lines._1}\n\t\t${lines._2}""".toString
          case t: ContainerType =>
            val lines = getInstructionsForContainerType(instruction, t, containerItems)
            lines.toString
        }

      case (false, Some(dtype), None) =>
        dtype match {
          case _: PrimitiveType =>
            val lines = getInstructionsForPrimitive(Implied)
            fast"""${lines._1}\n\t\t${lines._2}""".toString
          case t: DefinedType =>
            val lines = getInstructionsForTypeConstructor(Implied, t)
            fast"""${lines._1}\n\t\t${lines._2}""".toString
          case t: ContainerType =>
            val lines = getInstructionsForContainerType(Implied, t, containerItems)
            lines.toString
        }

      case _ =>
        throw new HarrowException(s"Failed to decode [$identifier] from [$noInput] with explicit type [${declaration.definition.datatype}] and codec [$inputInstr] at [${declaration.pos}]")

    }

    // generate complete field type.. with proper optional support note: optional lists/sets/maps are not wrapped.. 
    val field = (declaration.definition.scope, assignInstr) match {
      case (IsRequired, Some(condAssign)) =>
        throw new HarrowException(s"Failed to decode [$identifier].. Cannot have conditional assignment on a required field at [${declaration.pos}]")
      case (IsTransient, Some(ConditionalInput(expr))) if (!isCollection) =>
        val retType = getFlyTypeAsString(declaration.definition.datatype).map(s => fast":Option[$s]".toString).getOrElse("")
        fast"""\t$modifier ${declaration.definition.identifier} $retType = { \n\t\tif ($expr) {\n\t\tSome({\n\t\t$snippet\n\t\t})\n\t\t} else {\n\t\tNone \n\t\t} \n\t}"""
      case (IsOptional, Some(ConditionalInput(expr))) if (!isCollection) =>
        val retType = getFlyTypeAsString(declaration.definition.datatype).map(s => fast":Option[$s]".toString).getOrElse("")
        fast"""\t$modifier ${declaration.definition.identifier} $retType = { \n\t\tif ($expr) {\n\t\tSome({\n\t\t$snippet\n\t\t})\n\t\t} else {\n\t\tNone \n\t\t} \n\t}"""
      case (IsOptional, None) if (!isCollection) =>
        val retType = getFlyTypeAsString(declaration.definition.datatype).map(s => fast":Option[$s]".toString).getOrElse("")
        fast"""\t$modifier ${declaration.definition.identifier} $retType = { \n\t\tSome({\n\t\t$snippet\n\t\t}) \n\t}"""
      case (_, _) =>
        val retType = getFlyTypeAsString(declaration.definition.datatype).map(s => fast":$s".toString()).getOrElse("")
        fast"""\t$modifier ${declaration.definition.identifier} $retType = { \n\t\t$snippet	\n\t}"""
    }

    field.toString // field definition

  }

}
 