package harrow.core

import java.io.File
import com.dongxiguo.fastring.Fastring.Implicits._
import scala.Option.option2Iterable

/**
 * Code templates for standard Thrift IDL (derived from harrow DSL)
 */
object ThriftIDLTemplate {

  val comments = """/**
 * 
 * This code is generated.. Do not edit this file directly as changes will be lost
 *
 */"""

  class TypeScore(val definition: TDefinition, var score: Int)

  /**
   * sorts type definitions as required by thrift so that no
   * forward references are made..
   */
  def generate(model: HarrowData, destPackage: String = "", path: String = "", name: String = ""): Seq[File] = {

    val namespace = model.headers.collect{ case pkg: Namespace => pkg.path }.headOption.getOrElse(destPackage)
    
    require(!namespace.isEmpty(), { println("Thrift IDL generator :: package is required from either namespace header or explict arg") })
    require(!path.isEmpty(), { println("Thrift IDL generator :: path is required") })
    require(!name.isEmpty(), { println("Thrift IDL generator :: file name is required") })

    val includes = model.headers.collect { case inc: Include => inc }.map(i => fast"""include "${i.path}"""").mkString("\n")

    val scores = model.allTypes.map(t => t.identifier -> new TypeScore(t, 1)).toMap

    def doScores(definition: String) {
      scores(definition).definition match {
        case container: Struct =>
          container.fields.map(_.definition).collect {
            case FieldDefinition(_, _, _, Some(DefinedType(id))) => 
              doScores(id)
              id
            case FieldDefinition(_, _, _, Some(ListType(DefinedType(id)))) => 
              doScores(id)
              id
            case FieldDefinition(_, _, _, Some(SetType(DefinedType(id)))) => 
              doScores(id)
              id
          }.foreach(ref => {
             scores(ref).score += ( 1 + scores(container.identifier).score )
          })
        case _ =>
      }
    }
    model.allTypes.foreach(t => doScores(t.identifier))

    val byWeight = scores.values.toList.sortWith(_.score > _.score)
    val thriftDefs = byWeight.map(td => ThriftGenerator(td.definition).generate)

    val all = thriftDefs.mkString("\n\n")

    val f = new File(path, name.replaceAll("\\.[^.]*$", "") + ".thrift")
    val content = fast"$comments \nnamespace java ${namespace} \n\n${all}\n\n".toString()
    Some(new java.io.PrintWriter(f.getAbsolutePath())).foreach { f => try { f.write(content) } finally { f.close } }

    Seq(f)

  }

}

/**
 *
 */
trait ThriftGenerator {

  def generate: String

}

/*
 * 
 */
object ThriftGenerator {

  def apply(tdef: TDefinition): ThriftGenerator = {
    tdef match {
      case c: Struct => new ThriftTypeTemplate(c)
      case c: Const => new ThriftConstTemplate(c)
      case e: Enum => new ThriftEnumTemplate(e)
      case t: TypeDefAlias => new ThriftTypedefTemplate(t)
    }
  }

}

/**
 *
 */
class ThriftTypeTemplate(definition: Struct) extends ThriftGenerator {

  /**
   * builds a full type defintion from the template and the model
   */
  def generate = {

    // build field definitions
    val fieldDefs = definition.fields.flatMap(f => {
      val fType = f.definition.datatype.map(_.toString()).getOrElse("string")
      f.definition.scope match {
        case IsRequired | IsOptional =>
          Some(fast"${f.definition.numericId.getOrElse(0)}: ${f.definition.scope} $fType ${f.definition.identifier};")
        case _ =>
          None
      }
    }).mkString("\n\t", "\n\t", "\n")
    val typeName = if(definition.isUnion) "union" else "struct"
    fast"$typeName ${definition.identifier} { $fieldDefs }".toString()

  }

}

/**
 *
 */
class ThriftConstTemplate(definition: Const) extends ThriftGenerator {

  /**
   * builds a full type defintion from the template and the model
   */
  def generate = {
    fast"\n\nconst ${definition.typeInfo} ${definition.identifier} = ${definition.value}".toString()
  }

}

/**
 * Template for a thrift definition
 */
class ThriftEnumTemplate(definition: Enum) extends ThriftGenerator {

  /**
   * builds a full type defintion from the template and the model
   */
  def generate = {
    val fieldDefs = definition.fields.map(pair => fast"\n\t${pair._1} = ${pair._2}".toString()).mkString(",")
    fast"\n\nenum ${definition.identifier} {${fieldDefs}\n}".toString()
  }

}

/**
 * Template for a thrift definition
 */
class ThriftTypedefTemplate(definition: TypeDefAlias) extends ThriftGenerator {

  /**
   * builds a full type defintion from the template and the model
   */
  def generate = {
    fast"\n\ntypedef ${definition.targetType} ${definition.identifier} \n".toString()
  }

}
