package harrow.core

import com.dongxiguo.fastring.Fastring.Implicits._
import scala.collection.mutable.ListBuffer
import java.io.File
import org.apache.thrift.protocol.TType

/**
 * Code templates for a read-only TProtocol implementation in scala
 */
object TReadProtocolTemplate {

    val comments = """/**
 * 
 * This code is generated.. Do not edit this file directly as changes will be lost
 *
 */"""
      
  val baseImports = List(Import("harrow.core.TProtocolEOF"),
    Import("harrow.core.TProtocolStop"),
    Import("harrow.core.AsTProtocolData"),
    Import("org.apache.thrift.protocol.TField"),
    Import("org.apache.thrift.protocol.TList"),
    Import("org.apache.thrift.protocol.TStruct"),
    Import("org.apache.thrift.protocol.TType"))
    
  /**
   *
   */
  def generate(model: HarrowData, destPackage: String = "", path: String = "", lazyImmutable: Boolean = false): Seq[File] = {

    val namespace = model.headers.collect{ case pkg: Namespace => pkg.path }.headOption.getOrElse(destPackage)
    
    require(!namespace.isEmpty(), { println("TReadPrototcol generator :: package is required from either namespace header or explict arg") })
    require(!path.isEmpty(), { println("TReadProtocol generator :: path is required") })

    val all = model.allTypes.map(d => d.identifier -> d).toMap

    val imports = (model.headers.collect({ case imp: Import => imp }).toList ++ baseImports).map(i => fast"import ${i.path}")

    val classes = model.complexDefinitions.values.map(d => {
      val generator = new TReadsClassTemplate(d, lazyImmutable, model.order, all)
      (d.identifier, generator.generate)
    }).toList

    val fullPath = fast"${path}/${namespace.replace('.', '/')}/tprotocol".toString
    val destinationFolder = new File(fullPath)
    destinationFolder.mkdirs()
    
    classes.map(generated => {
      val file = new File(destinationFolder, generated._1 + "TReads.scala")
      val importsWithFly = (fast"import ${namespace}.flyweights.${generated._1}Fly".toString :: imports).mkString("\n")
      val content = fast"$comments \npackage ${namespace}.tprotocol \n\n$importsWithFly \n\n${generated._2}\n\n".toString()
      Some(new java.io.PrintWriter(file.getAbsolutePath())).foreach { f => try { f.write(content) } finally { f.close } }
      file
    })

  }

}

/**
 * Template for a stateful read-only TProtocol implementation over a custom binary format
 */
class TReadsClassTemplate(definition: Struct, lazyImmutable: Boolean, defaultOrder: ByteOrder, context: Map[String, TDefinition]) {

  val modifier = if (lazyImmutable) "lazy val" else "def"

  val commonFields = fast"""\t$modifier _noMoreFields = new TProtocolStop(nextTransition)\n\n\toverride def readStructBegin = new TStruct("${definition.identifier}")""".toString()

  val indexedFields = definition.fields.flatMap(field => {
    field.definition.scope match {
      case IsRequired | IsOptional =>
        Some(field)
      case _ => None
    }
  })//.sortWith((a, b) => a.definition.numericId.get < b.definition.numericId.get)

  /**
   * derive a type string from a FieldType
   */
  def getTTypeStringForField(datatype: FieldType): String = {
    val ttype = datatype match {
      case x: PrimitiveType =>
        x.toString().toUpperCase()
      case DefinedType(t) =>
        context(t) match {
          case Struct(_,_,_,true) => "union".toUpperCase()
          case s: Struct => "struct".toUpperCase()
          case c: Const => "const".toUpperCase()
          case e: Enum => "enum".toUpperCase()
          case x => x.toString().toUpperCase()
        }
      case ListType(_) =>
        "List".toUpperCase()
      case SetType(_) =>
        "Set".toUpperCase()
      case MapType(_, _) =>
        "Map".toUpperCase()
      case x: ContainerType =>
        x.toString.toUpperCase()
    }
    ttype
  }

  /**
   * builds a full class definition from the template and the model
   */
  def generate = {

    class ProtocolField(identifier: String, numericId: Int, typeInfo: FieldType, nextTransition: String, scope: FieldScope, conditional: Option[Expression] = None)

    val transitions = indexedFields.map(d => fast"${d.definition.identifier}Field".toString()) :+ "_noMoreFields"

    val fieldDefs = indexedFields.zip(transitions.drop(1)).map {

      case (field, transition) => {
        field.definition.datatype match {

          case Some(ListType(DefinedType(id))) =>
            val fieldBegin = fast"""override def readFieldBegin = new TField("${field.definition.identifier}", TType.LIST, ${field.definition.numericId.get})"""
            val listBegin = fast"override def readListBegin = new TList(TType.STRUCT, data.${field.definition.identifier}.size)"
            val pointer = fast"var _next: AsTProtocolData = $transition"
            val loop = fast"\t\tval dlist = data.${field.definition.identifier}.reverse.map(elem => {\n\t\tval treads = new ${id}TReads(elem, _next)\n\t\t_next = treads\n\t\ttreads\n\t\t}).reverse"
            val initialState = fast"def nextRead = dlist.head"
            fast"\t$modifier ${field.definition.identifier}Field = new AsTProtocolData { \n\t\t$fieldBegin \n\t\t$listBegin \n\t\t$pointer \n$loop \n\t\t$initialState \n\t}".toString

          case Some(ListType(x: PrimitiveType)) =>
            val fieldBegin = fast"""override def readFieldBegin = new TField("${field.definition.identifier}", TType.LIST, ${field.definition.numericId.get})"""
            val listBegin = fast"override def readListBegin = new TList(TType.${x.toString().toUpperCase()}, data.${field.definition.identifier}.size)"
            val pointer = fast"var _next: AsTProtocolData = $transition"
            val elementRead = fast"override def read${x.toString().capitalize} = elem"
            val loop = fast"\t\tval dlist = data.${field.definition.identifier}.reverse.map(elem => {\n\t\tval treads = new AsTProtocolData {\n\t\t$elementRead \n\t\tdef nextRead = _next \n\t\t}\n\t\t_next = treads\n\t\ttreads\n\t\t}).reverse"
            val initialState = fast"def nextRead = dlist.head"
            fast"\t$modifier ${field.definition.identifier}Field = new AsTProtocolData { \n\t\t$fieldBegin \n\t\t$listBegin \n\t\t$pointer \n$loop \n\t\t$initialState \n\t}".toString

          case Some(SetType(DefinedType(id))) =>
            val fieldBegin = fast"""override def readFieldBegin = new TField("${field.definition.identifier}", TType.SET, ${field.definition.numericId.get})"""
            val listBegin = fast"override def readSetBegin = new TSet(TType.STRUCT, data.${field.definition.identifier}.size)"
            val pointer = fast"var _next: AsTProtocolData = $transition"
            val loop = fast"\t\tval dlist = data.${field.definition.identifier}.reverse.map(elem => {\n\t\tval treads = new ${id}TReads(elem, _next)\n\t\t_next = treads\n\t\ttreads\n\t\t}).reverse"
            val initialState = fast"def nextRead = dlist.head"
            fast"\t$modifier ${field.definition.identifier}Field = new AsTProtocolData { \n\t\t$fieldBegin \n\t\t$listBegin \n\t\t$pointer \n$loop \n\t\t$initialState \n\t}".toString

          case Some(SetType(x: PrimitiveType)) =>
            val fieldBegin = fast"""override def readFieldBegin = new TField("${field.definition.identifier}", TType.SET, ${field.definition.numericId.get})"""
            val listBegin = fast"override def readListBegin = new TList(TType.STRUCT, data.${field.definition.identifier}.size)"
            val pointer = fast"var _next: AsTProtocolData = $transition"
            val elementRead = fast"override def read${x.toString().capitalize} = elem"
            val loop = fast"\t\tval dlist = data.${field.definition.identifier}.reverse.map(elem => {\n\t\tval treads = new AsTProtocolData {\n\t\t$elementRead \n\t\tdef nextRead = _next \n\t\t}\n\t\t_next = treads\n\t\ttreads\n\t\t}).reverse"
            val initialState = fast"def nextRead = dlist.head"
            fast"\t$modifier ${field.definition.identifier}Field = new AsTProtocolData { \n\t\t$fieldBegin \n\t\t$listBegin \n\t\t$pointer \n$loop \n\t\t$initialState \n\t}".toString

          case Some(MapType(k, v)) => // TODO add proper map support
            val fieldBegin = fast"""override def readFieldBegin = new TField("${field.definition.identifier}", TType.MAP, ${field.definition.numericId.get})"""
            val listBegin = fast"override def readMapBegin = new TMAP(TType.${k.toString().toUpperCase()}, TType.${v.toString().toUpperCase()}, ${field.definition.identifier}.size)"
            val initialState = fast"def nextRead = $transition"
            fast"\t$modifier ${field.definition.identifier}Field = new AsTProtocolData { \n\t\t$fieldBegin \n\t\t$listBegin \n\t\t$initialState \n\t}".toString

          case Some(DefinedType(id)) if (context(id) match { case Struct(_,_,_,true) => true case _ => false }) =>
            val isOptional =  (field.definition.scope == IsOptional) 
            val fieldBegin = fast"""override def readFieldBegin = new TField("${field.definition.identifier}", TType.STRUCT, ${field.definition.numericId.get})"""
            val initialState = fast"def nextRead = ${field.definition.identifier}TProto"
            if (isOptional) {
              val createStruct = fast"val ${field.definition.identifier}TProto = new ${id}TReads(exists, $transition)"
              val protocolReadOp = fast"new AsTProtocolData { \n\t\t\t\t$fieldBegin \n\t\t\t\t$createStruct\n\t\t\t\t$initialState \n\t\t\t}"
              fast"\t$modifier ${field.definition.identifier}Field = data.${field.definition.identifier} match {\n\t\tcase Some(exists) => \n\t\t\t$protocolReadOp \n\t\tcase None => \n\t\t\t$transition \n\t}".toString
            } else {
              val createStruct = fast"val ${field.definition.identifier}TProto = new ${id}TReads(data.${field.definition.identifier}, $transition)"
              fast"\t$modifier ${field.definition.identifier}Field = new AsTProtocolData { \n\t\t$fieldBegin \n\t\t$createStruct\n\t\t$initialState \n\t}".toString
            }
            
          case Some(DefinedType(id)) if (context(id).isInstanceOf[Struct]) =>
            val isOptional =  (field.definition.scope == IsOptional) 
            val fieldBegin = fast"""override def readFieldBegin = new TField("${field.definition.identifier}", TType.STRUCT, ${field.definition.numericId.get})"""
            val initialState = fast"def nextRead = ${field.definition.identifier}TProto"
            if (isOptional) {
              val createStruct = fast"val ${field.definition.identifier}TProto = new ${id}TReads(exists, $transition)"
              val protocolReadOp = fast"new AsTProtocolData { \n\t\t\t\t$fieldBegin \n\t\t\t\t$createStruct\n\t\t\t\t$initialState \n\t\t\t}"
              fast"\t$modifier ${field.definition.identifier}Field = data.${field.definition.identifier} match {\n\t\tcase Some(exists) => \n\t\t\t$protocolReadOp \n\t\tcase None => \n\t\t\t$transition \n\t}".toString
            } else {
              val createStruct = fast"val ${field.definition.identifier}TProto = new ${id}TReads(data.${field.definition.identifier}, $transition)"
              fast"\t$modifier ${field.definition.identifier}Field = new AsTProtocolData { \n\t\t$fieldBegin \n\t\t$createStruct\n\t\t$initialState \n\t}".toString
            }
            
            
          case Some(DefinedType(id)) if (context(id).isInstanceOf[Enum]) =>
            val isOptional = (field.definition.scope == IsOptional) 
            val fieldBegin = fast"""override def readFieldBegin = new TField("${field.definition.identifier}", TType.I32, ${field.definition.numericId.get})"""
            val initialState = fast"def nextRead = $transition"
            if (isOptional) {
              val readValue = fast"override def readI32 = exists.ordinal"
              val protocolReadOp = fast"new AsTProtocolData { \n\t\t\t\t$fieldBegin \n\t\t\t\t$readValue\n\t\t\t\t$initialState \n\t\t\t}"
              fast"\t$modifier ${field.definition.identifier}Field = data.${field.definition.identifier} match {\n\t\tcase Some(exists) => \n\t\t\t$protocolReadOp \n\t\tcase None => \n\t\t\t$transition \n\t}".toString
            } else {
              val readValue = fast"override def readI32 = data.${field.definition.identifier}"
              fast"\t$modifier ${field.definition.identifier}Field = new AsTProtocolData { \n\t\t$fieldBegin \n\t\t$readValue\n\t\t$initialState \n\t}"
            }

          case Some(x: PrimitiveType) =>
            val isOptional = (field.definition.scope == IsOptional) 
            val fieldBegin = fast"""override def readFieldBegin = new TField("${field.definition.identifier}", TType.${x.toString().toUpperCase()}, ${field.definition.numericId.get})"""
            val initialState = fast"def nextRead = $transition"
            if (isOptional) {
              val readValue = fast"override def read${x.toString().capitalize} = exists"
              val protocolReadOp = fast"new AsTProtocolData { \n\t\t\t\t$fieldBegin \n\t\t\t\t$readValue\n\t\t\t\t$initialState \n\t\t\t}"
              fast"\t$modifier ${field.definition.identifier}Field = data.${field.definition.identifier} match {\n\t\tcase Some(exists) => \n\t\t\t$protocolReadOp \n\t\tcase None => \n\t\t\t$transition \n\t}".toString
            } else {
              val readValue = fast"override def read${x.toString().capitalize} = data.${field.definition.identifier}"
              fast"\t$modifier ${field.definition.identifier}Field = new AsTProtocolData { \n\t\t$fieldBegin \n\t\t$readValue\n\t\t$initialState \n\t}"
            }

          case _ => ""
        }

      }
    }.mkString("\n\n")

    val initialTransition = fast"\tdef nextRead = ${transitions.head}"
    fast"\n\nclass ${definition.identifier}TReads(data: ${definition.identifier}Fly, nextTransition: AsTProtocolData = TProtocolEOF) extends AsTProtocolData { \n\n$commonFields \n\n$fieldDefs \n\n$initialTransition \n\n}".toString()

  }

}